export interface Resource {
  id: string
  title: string
  description: string
  type: "course" | "book" | "article" | "video" | "project" | "tool" | "documentation"
  category: string[]
  difficulty: "Beginner" | "Intermediate" | "Advanced"
  free: boolean
  url: string
  author: string
  rating: number
  duration?: string
  tags: string[]
  featured: boolean
}

export const resources: Resource[] = [
  {
    id: "r1",
    title: "The Odin Project",
    description:
      "Free full-stack curriculum with projects and community support. Covers HTML, CSS, JavaScript, React, Node.js, and more.",
    type: "course",
    category: ["full-stack", "frontend", "backend"],
    difficulty: "Beginner",
    free: true,
    url: "https://www.theodinproject.com",
    author: "The Odin Project",
    rating: 4.8,
    duration: "6-12 months",
    tags: ["HTML", "CSS", "JavaScript", "React", "Node.js", "Full-Stack"],
    featured: true,
  },
  {
    id: "r2",
    title: "freeCodeCamp",
    description:
      "Interactive coding challenges and certifications in web development, data science, and machine learning.",
    type: "course",
    category: ["full-stack", "frontend", "backend", "ml-engineer", "data-engineer"],
    difficulty: "Beginner",
    free: true,
    url: "https://www.freecodecamp.org",
    author: "freeCodeCamp",
    rating: 4.7,
    duration: "300+ hours per cert",
    tags: ["JavaScript", "Python", "React", "Data Science", "ML"],
    featured: true,
  },
  {
    id: "r3",
    title: "Next.js Documentation",
    description:
      "Official Next.js docs with tutorials, API reference, and best practices for building React applications.",
    type: "documentation",
    category: ["full-stack", "frontend"],
    difficulty: "Intermediate",
    free: true,
    url: "https://nextjs.org/docs",
    author: "Vercel",
    rating: 4.9,
    tags: ["Next.js", "React", "TypeScript", "Full-Stack"],
    featured: true,
  },
  {
    id: "r4",
    title: "LeetCode",
    description:
      "Practice coding problems and prepare for technical interviews with thousands of algorithm challenges.",
    type: "tool",
    category: ["full-stack", "frontend", "backend", "ml-engineer"],
    difficulty: "Intermediate",
    free: true,
    url: "https://leetcode.com",
    author: "LeetCode",
    rating: 4.6,
    tags: ["Algorithms", "Data Structures", "Interview Prep"],
    featured: false,
  },
  {
    id: "r5",
    title: "Designing Data-Intensive Applications",
    description: "Deep dive into the architecture of scalable systems, databases, and distributed computing.",
    type: "book",
    category: ["backend", "data-engineer", "cloud-architect"],
    difficulty: "Advanced",
    free: false,
    url: "https://dataintensive.net",
    author: "Martin Kleppmann",
    rating: 4.9,
    tags: ["System Design", "Databases", "Distributed Systems"],
    featured: true,
  },
  {
    id: "r6",
    title: "Fast.ai Practical Deep Learning",
    description: "Learn deep learning through practical projects. No PhD required, just basic Python knowledge.",
    type: "course",
    category: ["ml-engineer"],
    difficulty: "Intermediate",
    free: true,
    url: "https://course.fast.ai",
    author: "Jeremy Howard",
    rating: 4.8,
    duration: "7 weeks",
    tags: ["Deep Learning", "PyTorch", "ML", "AI"],
    featured: true,
  },
  {
    id: "r7",
    title: "Docker Documentation",
    description: "Official Docker docs covering containerization, Docker Compose, and deployment best practices.",
    type: "documentation",
    category: ["devops", "backend", "cloud-architect"],
    difficulty: "Intermediate",
    free: true,
    url: "https://docs.docker.com",
    author: "Docker",
    rating: 4.5,
    tags: ["Docker", "Containers", "DevOps"],
    featured: false,
  },
  {
    id: "r8",
    title: "React Native Documentation",
    description: "Build native mobile apps using React. Official docs with guides, API reference, and examples.",
    type: "documentation",
    category: ["mobile"],
    difficulty: "Intermediate",
    free: true,
    url: "https://reactnative.dev",
    author: "Meta",
    rating: 4.6,
    tags: ["React Native", "Mobile", "iOS", "Android"],
    featured: false,
  },
  {
    id: "r9",
    title: "OWASP Top 10",
    description: "Essential security awareness document for web application security vulnerabilities.",
    type: "article",
    category: ["security", "backend", "full-stack"],
    difficulty: "Intermediate",
    free: true,
    url: "https://owasp.org/www-project-top-ten",
    author: "OWASP",
    rating: 4.7,
    tags: ["Security", "Web Security", "Vulnerabilities"],
    featured: false,
  },
  {
    id: "r10",
    title: "Unity Learn",
    description: "Official Unity tutorials and courses for game development, from beginner to advanced.",
    type: "course",
    category: ["game-dev"],
    difficulty: "Beginner",
    free: true,
    url: "https://learn.unity.com",
    author: "Unity",
    rating: 4.5,
    duration: "Varies",
    tags: ["Unity", "Game Dev", "C#", "3D"],
    featured: false,
  },
  {
    id: "r11",
    title: "Embedded Systems Programming",
    description: "Comprehensive guide to embedded C programming and real-time operating systems.",
    type: "book",
    category: ["embedded"],
    difficulty: "Advanced",
    free: false,
    url: "https://example.com",
    author: "Michael Barr",
    rating: 4.6,
    tags: ["Embedded", "C", "RTOS", "Hardware"],
    featured: false,
  },
  {
    id: "r12",
    title: "CryptoZombies",
    description: "Learn Solidity by building your own crypto-collectibles game. Interactive and fun.",
    type: "course",
    category: ["blockchain"],
    difficulty: "Beginner",
    free: true,
    url: "https://cryptozombies.io",
    author: "Loom Network",
    rating: 4.7,
    duration: "10 hours",
    tags: ["Solidity", "Blockchain", "Smart Contracts", "Web3"],
    featured: false,
  },
  {
    id: "r13",
    title: "AWS Solutions Architect Path",
    description: "Comprehensive learning path for AWS cloud architecture and infrastructure design.",
    type: "course",
    category: ["cloud-architect", "devops"],
    difficulty: "Advanced",
    free: false,
    url: "https://aws.amazon.com/training",
    author: "AWS",
    rating: 4.7,
    duration: "40+ hours",
    tags: ["AWS", "Cloud", "Architecture", "Infrastructure"],
    featured: true,
  },
  {
    id: "r14",
    title: "SQL for Data Analysis",
    description: "Master SQL queries, joins, aggregations, and window functions for data analysis.",
    type: "course",
    category: ["data-engineer", "backend"],
    difficulty: "Beginner",
    free: true,
    url: "https://mode.com/sql-tutorial",
    author: "Mode Analytics",
    rating: 4.6,
    duration: "20 hours",
    tags: ["SQL", "Data Analysis", "Databases"],
    featured: false,
  },
  {
    id: "r15",
    title: "Tailwind CSS Documentation",
    description: "Utility-first CSS framework documentation with examples and best practices.",
    type: "documentation",
    category: ["frontend", "full-stack"],
    difficulty: "Beginner",
    free: true,
    url: "https://tailwindcss.com/docs",
    author: "Tailwind Labs",
    rating: 4.8,
    tags: ["CSS", "Tailwind", "Styling", "UI"],
    featured: false,
  },
  {
    id: "r16",
    title: "System Design Primer",
    description: "Learn how to design large-scale systems. Covers scalability, load balancing, caching, and more.",
    type: "article",
    category: ["backend", "cloud-architect"],
    difficulty: "Advanced",
    free: true,
    url: "https://github.com/donnemartin/system-design-primer",
    author: "Donne Martin",
    rating: 4.9,
    tags: ["System Design", "Scalability", "Architecture"],
    featured: true,
  },
  {
    id: "r17",
    title: "Build a Full-Stack App",
    description: "Step-by-step project tutorial to build a complete CRUD application with authentication.",
    type: "project",
    category: ["full-stack"],
    difficulty: "Intermediate",
    free: true,
    url: "https://example.com",
    author: "Web Dev Simplified",
    rating: 4.5,
    duration: "8 hours",
    tags: ["Full-Stack", "React", "Node.js", "MongoDB"],
    featured: false,
  },
  {
    id: "r18",
    title: "TypeScript Handbook",
    description: "Official TypeScript documentation covering types, interfaces, generics, and advanced patterns.",
    type: "documentation",
    category: ["frontend", "backend", "full-stack"],
    difficulty: "Intermediate",
    free: true,
    url: "https://www.typescriptlang.org/docs",
    author: "Microsoft",
    rating: 4.7,
    tags: ["TypeScript", "JavaScript", "Types"],
    featured: false,
  },
  {
    id: "r19",
    title: "Kubernetes Documentation",
    description: "Learn container orchestration with Kubernetes. Official docs with tutorials and concepts.",
    type: "documentation",
    category: ["devops", "cloud-architect"],
    difficulty: "Advanced",
    free: true,
    url: "https://kubernetes.io/docs",
    author: "Kubernetes",
    rating: 4.6,
    tags: ["Kubernetes", "DevOps", "Containers", "Orchestration"],
    featured: false,
  },
  {
    id: "r20",
    title: "Figma for Developers",
    description: "Learn how to use Figma to collaborate with designers and implement designs accurately.",
    type: "video",
    category: ["frontend"],
    difficulty: "Beginner",
    free: true,
    url: "https://www.youtube.com/figma",
    author: "Figma",
    rating: 4.5,
    duration: "2 hours",
    tags: ["Figma", "Design", "UI/UX", "Collaboration"],
    featured: false,
  },
]
